name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      # Remove Node.js setup and npm steps
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'
      # - run: npm ci
      # - run: npm run build

      # Add any necessary build steps here if required

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Ensure this directory exists and contains your site files
